language: node_js
node_js: stable

# assign build branches
branches:
  only:
    - hexo

# cache this directory
cache:
  directories:  # 这两个目录不用每次都更新
    #- node_modules
    #- themes

# S: Build Lifecycle
before_install:
  - npm install -g hexo-cli # install hexo
  #- git clone https://github.com/theme-next/hexo-theme-next themes/next 

install:
  - npm install # install by package.json

script:
  - hexo generate

after_success:
  - git config --global user.name "memorywalker"
  - git config --global user.email "eddy.wd5@gmail.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" _config.yml #使用travisCI中配置的token替换掉_config.yml中对应的占位符
  - hexo deploy
# E: Build LifeCycle
